import type { Locale } from "@/lib/site-i18n";

/**
 * Region hub model for Melbourne suburbs. There are ~248 active service-area
 * suburbs in `public.suburbs`; rather than a thin page per suburb, we group them
 * into 9 named Melbourne regions. Each region gets ONE rich landing page that
 * lists every suburb it covers (capturing the long-tail "{suburb} second hand"
 * keywords) without hundreds of near-duplicate pages.
 *
 * The 8 existing city/inner suburb pages (CBD, Carlton, Parkville, Southbank,
 * Docklands, Fitzroy, North Melbourne, South Wharf) are kept AS-IS and simply
 * linked from within their region's suburb list (see EXISTING_SUBURB_PAGES).
 *
 * IMPORTANT: `suburbs` entries must exactly match `public.suburbs.name`. The set
 * across all regions must be an exact partition of the active suburbs — verified
 * by scripts against Supabase. Do not edit names casually.
 */

export const REGION_SLUGS = [
  "inner-north",
  "inner-east",
  "inner-south",
  "eastern",
  "south-east",
  "bayside",
  "northern",
  "north-west",
  "western",
] as const;

export type RegionSlug = (typeof REGION_SLUGS)[number];

export type MelbourneRegion = {
  slug: RegionSlug;
  /** Short geographic label per locale, interpolated into page copy. */
  names: Record<Locale, string>;
  /** Exact `public.suburbs.name` values that belong to this region. */
  suburbs: string[];
};

/** DB suburb name → existing dedicated suburb page path (kept as-is, linked in). */
export const EXISTING_SUBURB_PAGES: Record<string, string> = {
  "Melbourne CBD": "/melbourne-suburbs/melbourne-cbd",
  Carlton: "/melbourne-suburbs/carlton",
  Parkville: "/melbourne-suburbs/parkville",
  Southbank: "/melbourne-suburbs/southbank",
  Docklands: "/melbourne-suburbs/docklands",
  Fitzroy: "/melbourne-suburbs/fitzroy",
  "North Melbourne": "/melbourne-suburbs/north-melbourne",
  "South Wharf": "/melbourne-suburbs/south-wharf",
};

export const MELBOURNE_REGIONS: MelbourneRegion[] = [
  {
    slug: "inner-north",
    names: {
      en: "Inner North",
      "zh-Hans": "内北区",
      "zh-Hant": "內北區",
      ko: "이너 노스(도심 북부)",
      ja: "インナーノース（都心北）",
      vi: "Inner North (bắc nội đô)",
      fr: "Inner North (nord central)",
      es: "Inner North (norte central)",
    },
    suburbs: [
      "Abbotsford",
      "Alphington",
      "Brunswick",
      "Brunswick East",
      "Brunswick West",
      "Carlton",
      "Carlton North",
      "Clifton Hill",
      "Coburg",
      "Coburg North",
      "Collingwood",
      "Fairfield",
      "Fitzroy",
      "Fitzroy North",
      "North Melbourne",
      "Northcote",
      "Parkville",
      "Preston",
      "Princes Hill",
      "Thornbury",
      "West Melbourne",
    ],
  },
  {
    slug: "inner-east",
    names: {
      en: "Inner East",
      "zh-Hans": "内东区",
      "zh-Hant": "內東區",
      ko: "이너 이스트(도심 동부)",
      ja: "インナーイースト（都心東）",
      vi: "Inner East (đông nội đô)",
      fr: "Inner East (est central)",
      es: "Inner East (este central)",
    },
    suburbs: [
      "Balwyn",
      "Balwyn North",
      "Burnley",
      "Camberwell",
      "Canterbury",
      "Cremorne",
      "Deepdene",
      "Glen Iris",
      "Hawthorn",
      "Hawthorn East",
      "Kew",
      "Kew East",
      "Kooyong",
      "Mont Albert",
      "Mont Albert North",
      "Richmond",
      "Surrey Hills",
    ],
  },
  {
    slug: "inner-south",
    names: {
      en: "Inner South",
      "zh-Hans": "内南区",
      "zh-Hant": "內南區",
      ko: "이너 사우스(도심 남부)",
      ja: "インナーサウス（都心南）",
      vi: "Inner South (nam nội đô)",
      fr: "Inner South (sud central)",
      es: "Inner South (sur central)",
    },
    suburbs: [
      "Albert Park",
      "Armadale",
      "Balaclava",
      "Docklands",
      "East Melbourne",
      "Elwood",
      "Malvern",
      "Malvern East",
      "Melbourne CBD",
      "Middle Park",
      "Port Melbourne",
      "Prahran",
      "Ripponlea",
      "South Melbourne",
      "South Wharf",
      "South Yarra",
      "Southbank",
      "St Kilda",
      "St Kilda East",
      "St Kilda West",
      "Toorak",
      "Windsor",
    ],
  },
  {
    slug: "eastern",
    names: {
      en: "Eastern Suburbs",
      "zh-Hans": "东区",
      "zh-Hant": "東區",
      ko: "이스턴(동부)",
      ja: "イースタン（東部）",
      vi: "Khu Đông (Eastern)",
      fr: "Banlieue Est",
      es: "Suburbios del Este",
    },
    suburbs: [
      "Ashburton",
      "Ashwood",
      "Bayswater",
      "Blackburn",
      "Blackburn North",
      "Blackburn South",
      "Box Hill",
      "Box Hill North",
      "Box Hill South",
      "Bulleen",
      "Burwood",
      "Burwood East",
      "Doncaster",
      "Doncaster East",
      "Donvale",
      "Forest Hill",
      "Glen Waverley",
      "Heathmont",
      "Knoxfield",
      "Lysterfield South",
      "Mitcham",
      "Mount Waverley",
      "North Warrandyte",
      "Nunawading",
      "Park Orchards",
      "Ringwood",
      "Ringwood East",
      "Ringwood North",
      "Rowville",
      "Scoresby",
      "Templestowe",
      "Templestowe Lower",
      "Vermont",
      "Vermont South",
      "Wantirna",
      "Wantirna South",
      "Warrandyte",
      "Warrandyte South",
      "Warranwood",
      "Wonga Park",
    ],
  },
  {
    slug: "south-east",
    names: {
      en: "South East",
      "zh-Hans": "东南区",
      "zh-Hant": "東南區",
      ko: "사우스 이스트(남동부)",
      ja: "サウスイースト（南東部）",
      vi: "Khu Đông Nam (South East)",
      fr: "Sud-Est",
      es: "Sudeste",
    },
    suburbs: [
      "Bentleigh",
      "Bentleigh East",
      "Braeside",
      "Carnegie",
      "Caulfield",
      "Caulfield East",
      "Caulfield North",
      "Caulfield South",
      "Chadstone",
      "Clarinda",
      "Clayton",
      "Clayton South",
      "Dandenong",
      "Dandenong North",
      "Dandenong South",
      "Dingley Village",
      "Doveton",
      "Elsternwick",
      "Endeavour Hills",
      "Eumemmerring",
      "Gardenvale",
      "Glen Huntly",
      "Hallam",
      "Heatherton",
      "Hughesdale",
      "Huntingdale",
      "Keysborough",
      "Mckinnon",
      "Moorabbin",
      "Moorabbin Airport",
      "Mulgrave",
      "Murrumbeena",
      "Noble Park",
      "Noble Park North",
      "Notting Hill",
      "Oakleigh",
      "Oakleigh East",
      "Oakleigh South",
      "Ormond",
      "Springvale",
      "Springvale South",
      "Wheelers Hill",
    ],
  },
  {
    slug: "bayside",
    names: {
      en: "Bayside",
      "zh-Hans": "海湾区",
      "zh-Hant": "海灣區",
      ko: "베이사이드",
      ja: "ベイサイド",
      vi: "Bayside (ven vịnh)",
      fr: "Bayside (bord de baie)",
      es: "Bayside (zona de la bahía)",
    },
    suburbs: [
      "Beaumaris",
      "Black Rock",
      "Brighton",
      "Brighton East",
      "Cheltenham",
      "Hampton",
      "Hampton East",
      "Highett",
      "Mentone",
      "Mordialloc",
      "Parkdale",
      "Sandringham",
    ],
  },
  {
    slug: "northern",
    names: {
      en: "Northern Suburbs",
      "zh-Hans": "北区",
      "zh-Hant": "北區",
      ko: "노던(북부)",
      ja: "ノーザン（北部）",
      vi: "Khu Bắc (Northern)",
      fr: "Banlieue Nord",
      es: "Suburbios del Norte",
    },
    suburbs: [
      "Bellfield",
      "Briar Hill",
      "Broadmeadows",
      "Bundoora",
      "Campbellfield",
      "Diamond Creek",
      "Eaglemont",
      "Eltham",
      "Eltham North",
      "Fawkner",
      "Glenroy",
      "Greensborough",
      "Hadfield",
      "Heidelberg",
      "Heidelberg Heights",
      "Heidelberg West",
      "Ivanhoe",
      "Ivanhoe East",
      "Jacana",
      "Kangaroo Ground",
      "Kingsbury",
      "Lower Plenty",
      "Macleod",
      "Montmorency",
      "Plenty",
      "Research",
      "Reservoir",
      "Rosanna",
      "St Helena",
      "Thomastown",
      "Viewbank",
      "Watsonia",
      "Watsonia North",
      "Wattle Glen",
      "Yallambie",
    ],
  },
  {
    slug: "north-west",
    names: {
      en: "North West",
      "zh-Hans": "西北区",
      "zh-Hant": "西北區",
      ko: "노스 웨스트(북서부)",
      ja: "ノースウエスト（北西部）",
      vi: "Khu Tây Bắc (North West)",
      fr: "Nord-Ouest",
      es: "Noroeste",
    },
    suburbs: [
      "Aberfeldie",
      "Airport West",
      "Ascot Vale",
      "Avondale Heights",
      "Essendon",
      "Essendon Fields",
      "Essendon North",
      "Essendon West",
      "Flemington",
      "Gladstone Park",
      "Gowanbrae",
      "Keilor",
      "Keilor Downs",
      "Keilor East",
      "Keilor Lodge",
      "Keilor North",
      "Keilor Park",
      "Kensington",
      "Melbourne Airport",
      "Moonee Ponds",
      "Niddrie",
      "Oak Park",
      "Pascoe Vale",
      "Pascoe Vale South",
      "Strathmore",
      "Strathmore Heights",
      "Travancore",
      "Tullamarine",
      "Westmeadows",
    ],
  },
  {
    slug: "western",
    names: {
      en: "Western Suburbs",
      "zh-Hans": "西区",
      "zh-Hant": "西區",
      ko: "웨스턴(서부)",
      ja: "ウエスタン（西部）",
      vi: "Khu Tây (Western)",
      fr: "Banlieue Ouest",
      es: "Suburbios del Oeste",
    },
    suburbs: [
      "Albion",
      "Altona",
      "Altona Meadows",
      "Altona North",
      "Ardeer",
      "Braybrook",
      "Brooklyn",
      "Cairnlea",
      "Derrimut",
      "Footscray",
      "Kealba",
      "Kingsville",
      "Laverton North",
      "Maidstone",
      "Maribyrnong",
      "Newport",
      "Point Cook",
      "Seaholme",
      "Seddon",
      "South Kingsville",
      "Spotswood",
      "St Albans",
      "Sunshine",
      "Sunshine North",
      "Sunshine West",
      "Tottenham",
      "West Footscray",
      "Williamstown",
      "Williamstown North",
      "Yarraville",
    ],
  },
];

export function getRegion(slug: string): MelbourneRegion | null {
  return MELBOURNE_REGIONS.find((r) => r.slug === slug) ?? null;
}

/** Logical region paths (locale-less) for sitemap + hub links. */
export function regionPaths(): string[] {
  return MELBOURNE_REGIONS.map((r) => `/melbourne-suburbs/${r.slug}`);
}
